spring.application.name=Example
server.port=8081

spring.datasource.url=jdbc:sqlserver://localhost:1433;trustServerCertificate=true;encrypt=true;integratedSecurity=false;databaseName=HardwareShop;
spring.datasource.username=sa
spring.datasource.password=SQL
